name: Run Sentiment Pipeline and Commit Results

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours UTC
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download NLTK data
      run: |
        python -m nltk.downloader punkt stopwords vader_lexicon punkt_tab
        echo "NLTK_DATA=/home/runner/nltk_data" >> $GITHUB_ENV

    - name: Set NLTK_DATA path
      run: echo "NLTK_DATA=/home/runner/nltk_data" >> $GITHUB_ENV

    - name: Run sentiment pipeline
      run: python main.py

    - name: Commit updated results.json
      run: |
        git config --global user.name 'EDGARDEVEN'
        git config --global user.email 'edgardeven303@gmail.com'
        git add -A
        git commit -m " Update sentiment results [auto]" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
      
